### ISSUE TITLE
ignore nodes with state==enroll

### ISSUE THREAD

**Issue by stefanhipfel** [sapcc/ipmi_sd#14]
Nodes which are in state "enroll" should be ignored since: 

> Nodes in this state are not available for deployment, nor for most of other actions. Ironic does not touch such nodes in any way.

**Comment by stefanhipfel** [comment]
@BerndKue what are your thoughts on this?

**Comment by BerndKue** [comment]
during build up the first state of the machines is enrolled.
But at this time there might be no used configured yet on the remote board for IPMI access.
Later we need to find hardware issues before handing over the machines.
This can still be done when the machine are in managable state.
Hence I think it is right to ignore all errors for machines in enroll state.

**Comment by stefanhipfel** [comment]
This is for the service discovery. He will not list nodes (which are enroll state) as targets. Since those have no ipmi configured and are reported as down atm.

As soon as the state > enroll, nodes will be listed as targets

**Comment by BerndKue** [comment]
Makes sense

**Comment by stefanhipfel** [comment]
Done with last PR
